### ISSUE TITLE
reboots to nor

### ISSUE THREAD

**Issue by sensorii** [gl-inet/lede-imagebuilder-ar71xx-nand#1]
probably needs [this fix](https://github.com/gl-inet/lede-17.01/commit/ecd6dd02b1ca9968b4e2850889b66196adc606bf)

**Comment by kysonlok** [comment]
@sensorii Thanks for your attention, I have fixed this. This is only change the config partition to write, it is nothing to reboot to nor. If reboot to nor, it seems your unit fail to try to boot from nand third, you can try to reboot again.

**Comment by sensorii** [comment]
@kysonlok thanks!
now this line in /etc/diag.sh will succeed:
`fw_printenv lc >/dev/null 2>&1 && fw_setenv "bootcount" 0`
this fixed my issue so I close issue.
