### ISSUE TITLE
Video webcam feature missing

### ISSUE THREAD

**Issue by sensorii** [gl-inet/lede-imagebuilder-ar71xx-nand#2]
I noticed that the webcam Video icon and page was missing from the gl-inet interface in the 2.27 version compared to 2.264.

While I was building images, I tried some things.
Adding `luci-app-mjpg-streamer` to the list of packages enabled video section in the interface.  I also see that `mjpg-streamer` is installed on the router.  However, when a USB webcam is plugged into the router, the page says _"Cannot find any video device"_.  I'm not sure what else it needs, this webcam has worked with gl-inet routers before for that feature.

**Comment by kysonlok** [comment]
@sensorii Thanks for your attention, I have update images.json. You should issue `git pull`, and try to build again.

**Comment by sensorii** [comment]
With updates the video device is now found, but no stream is displayed:

![screenshot_2018-01-23_21-13-39](https://user-images.githubusercontent.com/4344597/35315746-e55a75f6-0082-11e8-9796-c9023ef7aef9.png)

more info:
```
root@GL-AR300M:~# dmesg | tail -n5
[   59.376727] random: nonblocking pool is initialized
[  144.736759] usb 1-1: new high-speed USB device number 2 using ehci-platform
[  144.961385] uvcvideo: Found UVC 1.00 device USB2.0 Camera (1e4e:0109)
[  144.977457] uvcvideo: UVC non compliance - GET_DEF(PROBE) not supported. Enabling workaround.
[  144.997076] input: USB2.0 Camera as /devices/platform/ehci-platform/usb1/1-1/1-1:1.0/input/input0
root@GL-AR300M:~# ls -l /dev/video0 
crw-------    1 root     root       81,   0 Jan 23 21:12 /dev/video0
```

**Comment by kysonlok** [comment]
Are you sure you have updated this commit? [9929cb472](https://github.com/gl-inet/lede-imagebuilder-ar71xx-nand/commit/9929cb472e8dd3d7fc49f5ffa21ca83953676f14). You must be updated mjpg-streamer ipk.

**Comment by sensorii** [comment]
yes, I built an image from 9ea38b4bd2c9a1063c300b7fe417fe5fc6aa38e2.  I did add 3 packages to the `v1` image but none that should matter for mjpg.

`/usr/bin/video_init` is missing:
```
root@GL-AR300M:~# /etc/init.d/mjpg-streamer restart
/etc/rc.common: line 1: /usr/bin/video_init: not found
root@GL-AR300M:~# ls /usr/bin/video_init
ls: /usr/bin/video_init: No such file or directory
```

Testing with 2 USB web cams that work on old firmware, including when booting to v2.20 nor on the same router.  in the old firmware, there is `/usr/bin/video_init` file.

**Comment by kysonlok** [comment]
That's strange. It is fine for my testing, although encounter with the same error.  
```bash  
root@GL-AR300M:/# /etc/init.d/mjpg-streamer restart
/etc/rc.common: line 1: /usr/bin/video_init: not found
```  

![image](https://user-images.githubusercontent.com/25576728/35321414-dd7befd2-0121-11e8-8c95-a2796801ea6e.png)

**Comment by kysonlok** [comment]
You can try to access webcam from the url: your local ip:8083, for me 192.168.8.1:8083. Maybe it works fine.

**Comment by sensorii** [comment]
cool, yours works. mine still does not. I just build a fresh image exactly from `v1` with no additional packages and still not working.  Where yours says _Integrated_Webcam_, mine says _USB 2.0 Camera_.

Is your `/dev/video` device readable by others?  I noticed the old (working) firmware has:
```
root@GL-AR300M:~# ls -l /dev/video0 
crw-r--r--    1 root     root       81,   0 Jul  1 21:38 /dev/video0
```
and my new one has:
```
root@GL-AR300M:~# ls -l /dev/video0 
crw-------    1 root     root       81,   0 Jan 23 21:16 /dev/video0
```

I manually changed that, but did not matter.  I wonder if missing `video_init` file sets permissions or something else.

Loading `192.168.8.1:8083` is blank page.
Watching logs reveals a crash:
```
root@GL-AR300M:~# logread -f
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: starting application
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: MJPG Streamer Version: svn rev: Unversioned directory
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: Using V4L2 device.: /dev/video0
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: Desired Resolution: 320 x 240
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: Frames Per Second.: 15
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: Format............: JPEG
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: TV-Norm...........: DEFAULT
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: www-folder-path...: /www/webcam/
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: HTTP TCP port.....: 8083
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: username:password.: disabled
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: commands..........: enabled
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: starting input plugin input_uvc.so
Wed Jan 24 00:38:38 2018 user.info MJPG-streamer [12704]: starting output plugin: output_http.so (ID: 00)
Wed Jan 24 00:38:39 2018 user.info MJPG-streamer [12704]: serving client: 127.0.0.1

Wed Jan 24 00:38:49 2018 user.info MJPG-streamer [12704]: serving client: 192.168.8.216
Wed Jan 24 00:38:49 2018 user.info MJPG-streamer [12704]: serving client: 192.168.8.216
Wed Jan 24 00:38:49 2018 kern.info kernel: [  586.004521] 
Wed Jan 24 00:38:49 2018 kern.info kernel: [  586.004521] do_page_fault(): sending SIGSEGV to mjpg_streamer for invalid read access from 76e9e000
Wed Jan 24 00:38:49 2018 kern.info kernel: [  586.013998] epc = 76f0a07b in output_http.so[76f06000+16000]
Wed Jan 24 00:38:49 2018 kern.info kernel: [  586.019922] ra  = 76f0a049 in output_http.so[76f06000+16000]
Wed Jan 24 00:38:49 2018 kern.info kernel: [  586.025829] 

```

**Comment by kysonlok** [comment]
I have updated gl-inet ipk, fix missing video_init binary. You can try again. Thanks!

**Comment by sensorii** [comment]
Fixed!  both USB cams work like they did with previous firmware.
now I close this issue.  Thanks! :smiley: 

![screenshot_2018-01-24_12-12-01](https://user-images.githubusercontent.com/4344597/35354994-c526f394-0100-11e8-8719-d50f56cb9d2f.png)

**Comment by kysonlok** [comment]
Yes, it does.
